### PR TITLE
feat(layout): minor adjustment to layout config

### PR DESCRIPTION
**Pull request by DOD-101**
This addresses the first request in #535.  

> 1. Remove columns

The change is mainly in adjusting how the borders are drawn.

It doesn't address the second request:

> Add different columns to replace them 

It might also be a good idea to implement some guard clauses to prevent the unseen windows from being rendered etc.

### CODE REVIEW

**Comment by NickTheWilder** [comment]
(New to rust so bear with me)

I'd like to test this since it's a feature I requested to at least contribute what I can. How could I do that? 
Is there already a contributing/how-to-build-locally doc that I'm missing?

I run `cargo b` to build the application, and then `cargo r` to run and I get the errors:

image

Cargo version: `cargo 1.80.1 (376290515 2024-07-16)`
Git: `2.46.0 (latest version)`

**Comment by DOD-101** [comment]
That's strange. There shouldn't be any errors. (Especially since all the checks are passing)

Try running `git diff` / `git status` to see if something may have accidental changed. 

> Is there already a contributing/how-to-build-locally doc that I'm missing?

Not that I know of.

Tip: You can just run cargo r(un). It will build and then run.

**Review by aome510 — COMMENTED** [review]
I don't think increasing other windows' size to "remove" a column is a good idea. The column is not really removed, it's just hidden from the UI. `FocusNextWindow` still points to the "hidden" window, which is confusing.

**Comment by DOD-101** [comment]
Do you think we should have a separate config option for this, or do we have an internal check if any column has a width of 0 and then skip any code relating to?
 
I think the option of an internal check would be better, since it's less config for the user to write.

**Comment by DOD-101** [comment]
Closing in favor of #567

**Pull request closed without merging**
