### PR TITLE
Add `lyric_finder` lib crate

### PR DESCRIPTION
**Pull request by aome510**
Implemented the `lyric_finder` crate that retrieves a song's lyric using https://genius.com and its APIs

### CODE REVIEW

**Comment by slikie** [comment]
Is lyric_finder still working with its aggressive cloudflare captcha policy? I can't seem to be able to get the example working.

**Comment by slikie** [comment]
A possible solution - multiple API used by https://github.com/spicetify/spicetify-cli/tree/master/CustomApps/lyrics-plus

**Comment by aome510** [comment]
@slikie I never have a trouble with scrapping lyric from genius.com. Which command did you use to run the example? I use

```
cargo run --example lyric-finder -- 'run taylor swift'
```

I'm not familiar with the "aggressive cloudflare captcha policy" you're referring to.

**Comment by slikie** [comment]
same as in the log - 
`30:2023-03-04T12:08:13.305693Z ERROR client_request{request=GetLyric { track: "Kill V. Maim", artists: "Grimes" }}: spotify_player::client::handlers: Failed to handle client request: failed to get lyric for track Kill V. Maim - artists Grimes: error decoding response body: expected value at line 1 column 1: expected value at line 1 column 1`


I have given up using genius with this popping up all the time. image

curling genius.com having similar result.

**Comment by aome510** [comment]
I see what you mean. Will take a look into the other solution you send. Can you create an issue for tracking?

**Pull request merged**
