### PR TITLE
Adding Homebrew Installation

### PR DESCRIPTION
**Pull request by slano-ls**

### CODE REVIEW

**Comment by aome510** [comment]
Thanks for the PR. Aren't you supposed to make a PR in the https://github.com/Homebrew/homebrew-core instead, as mentioned in https://github.com/aome510/spotify-player/issues/189#issuecomment-1537426696?

Also, let's wait for the new release with M1 binary support in release (https://github.com/aome510/spotify-player/issues/191) before adding a Homebrew support

**Comment by slano-ls** [comment]
I'll do that as well, the merging sometimes takes a while so using the tap works in a similar manner

**Comment by tresni** [comment]
https://github.com/Homebrew/homebrew-core/pull/128997

**Comment by aome510** [comment]
Close this for now as https://github.com/Homebrew/homebrew-core/pull/128997 is merged. Thanks @tresni.

I did try installing the app using `brew install spotify_player` and it works perfectly!

**Pull request closed without merging**
