### PR TITLE
Implement notification support

### LINKED ISSUE #123: feature request: notifications for tracks
The official Spotify client (on linux) sends notifications when a new track is played, or when you reach the end of a song, and the next one starts playing. It would be great if this could be added to `spotify-player` :point_right: :point_left: 

Here's an example of how it looks like with the official client:
image

### PR DESCRIPTION
**Pull request by aome510**
Resolves #123 

## Changes

- added `notify` feature (with `notify_rust` as dependencies) for desktop notification support
- saved downloaded cover images into `$APP_CACHE_FOLDER/image`

### CODE REVIEW

**Comment by apprehensions** [comment]
seems to work, but it seems that the format of the notification is hardset, and i would suggest it could be modified (although, the current is pretty good!)

it seems that the D-Bus `PlayBackStatus` when spotify_player is playing a song is constantly being set, and i would suggest it be sent once; as i've never seen the D-Bus requests like this on any music player (including Spotify itself)

as for the cache, it technically works, but the way to get the 'latest' album cover is via linux's `ctime` (creation time) or parsing the current song and formatting (not possible in spotify_player yet) it to the appropriate file name.

**Comment by apprehensions** [comment]
another feature i find cool is that the icon of the current playing song is passed to the D-Bus notification from the cache image file rather than encoded data (as seen in most applications; the output from `dbus-monitor` when an image is encoded in the request is 5171 lines long.).

**Comment by aome510** [comment]
> seems to work, but it seems that the format of the notification is hardset, and i would suggest it could be modified (although, the current is pretty good!)

Yeah, making the notification format configurable is not in the scope of this PR, maybe a follow-up PR. Do u have any suggestions on another format? Currently the format is "{name} • {artists}" as the summary and "{album}" as the body.

> it seems that the D-Bus PlayBackStatus when spotify_player is playing a song is constantly being set, and i would suggest it be sent once; as i've never seen the D-Bus requests like this on any music player (including Spotify itself)

Does it happen outside this PR or only with this PR? Also, not too familiar with D-BUS, how did you know that it's constantly being set?

> as for the cache, it technically works, but the way to get the 'latest' album cover is via linux's ctime (creation time) or parsing the current song and formatting (not possible in spotify_player yet) it to the appropriate file name.

I have an exactly same thought. `ctime` doesn't really work if you play cached track the second time. So I guess we should wait for #111.

> another feature i find cool is that the icon of the current playing song is passed to the D-Bus notification from the cache image file rather than encoded data (as seen in most applications; the output from dbus-monitor when an image is encoded in the request is 5171 lines long.).

I'm not sure what you mean by this. Do you mind to elaborate further?

**Comment by apprehensions** [comment]
> Does it happen outside this PR or only with this PR? Also, not too familiar with D-BUS, how did you know that it's constantly being set?

`dbus-monitor`

> I'm not sure what you mean by this. Do you mind to elaborate further?

don't worry about it, it was just a compliment.

**Comment by aome510** [comment]
> actually, happens with vanilla as well.

Interesting, will take a look.

> don't worry about it, it was just a compliment

Oh ok, ty <3. I initially thought you requested for a new feature

**Comment by aome510** [comment]
image

**Comment by aome510** [comment]
@apprehensions regarding the `PlaybackStatus` change thingy, this happened because `PlaybackStatus` is coupled with the playback's progress for reporting `position` and the status change is always emitted without checking the previous value as in https://github.com/Sinono3/souvlaki/blob/3b5d66fc4035b7a1e7ffa899a1636a3ce10a2571/src/platform/mpris/dbus.rs#L429-L433

So there's nothing much I can do with `spotify-player`. I would suggest raising issue or making a PR in the `souvlaki` repo if this really annoys you.

**Pull request merged**
