### PR TITLE
fix: switch to librespot 0.5.0

### LINKED ISSUE #520: Authentication failed: Bad credentials
Hi. I installed spotify-player but I get Bad credentials error. 
I entered the correct username and password and I have Premium account, too, but it failed. 
Can you help me fix this?

### LINKED ISSUE #579: Spotify session randomly invalidated
**Describe the bug**
While i sit on my chair, enjoying my music, i suddenly realize that the music stopped, with no clear indication as to why, and i am forced to replay the same song, knowing it will never hit the same again, because it was interrupted.

**To Reproduce**
Play music.

**Expected behaviour**
I continue hearing the music

**Log and backtrace**
```
2024-10-16T12:08:49.080339Z  INFO spotify_player::streaming: Got a new player event: Changed { old_track_id: TrackId("6vMib26W91Ue1PbFilnJfu"), new_track_id: TrackId("4x6duj3S7xHFhEUfDSbWgQ") }
2024-10-16T12:08:50.215753Z  INFO spotify_player::streaming: Got a new player event: Playing { track_id: TrackId("4x6duj3S7xHFhEUfDSbWgQ"), position_ms: 0, duration_ms: 892853 }
2024-10-16T12:08:51.025125Z  INFO client_request{request=GetCurrentUserQueue}: spotify_player::client: Successfully handled the client request, took: 575ms
2024-10-16T12:19:57.181822Z  INFO spotify_player::client: Client's current session is invalid, creating a new session...
2024-10-16T12:19:57.926983Z  INFO spotify_player::auth: Successfully used the cached credentials to create a new session!
2024-10-16T12:19:57.927140Z  INFO spotify_player::client: Used a new session for Spotify client.
```

**Environment**

- OS: Alpine Linux edge
- Application version: `"spotify_player 0.19.1 (git+https://github.com/aome510/spotifyplayer#8dcbc225cafd179b84b261b56ab1620dfcac1fc9)" = ["spotify_player"]`
- Application features: `pulseaudio-backend,streaming,lyric-finder,media-control,sixel,notify`

**Additional context**
It happened again as i was making this issue.

### LINKED ISSUE #580: [bug] Authentication Issues
this issue is a write-up of #520 due to that issue being way too long and tiring to read.

## summary
spotify deprecated the login api used for authentication.
**therefore, it is currently impossible to log in with the existing master branch/any version of spotify-player**
a fix is being worked on in #570, the pr can be used for basic functionality, some issues remain.
feel free to contribute by working on the pr or submitting new problems that arise when using spotify-player built from it!

## workaround
in an environment with a (somewhat up to date) rust toolchain set up, run the following commands in your home directory:
```sh
# build the librespot binary, we need this to generate credentials
git clone https://github.com/librespot-org/librespot.git
cd librespot
cargo build --release --no-default-features
# generate the credentials by running the program we just built
./target/release/librespot --cache ~/.cache/spotify-player/ -j
# Open or copy a link and login to Spotify as usual (this is the new login flow)
...
# cleanup once you've successfully logged in
cd ~
rm -rf ./librespot
# you should now be able to run spotify-player
spotify_player
```
huge thanks to the [original authors](https://github.com/aome510/spotify-player/issues/520#issuecomment-2389486176) and the [modification](https://github.com/aome510/spotify-player/issues/520#issuecomment-2407187864)! :heart:

## technical details
spotify now requires an oauth2 login flow, which needs to implemented.
the library used for authentication is [librespot](https://github.com/librespot-org/librespot), the dependency needs to be updated to the latest release which adds support for oauth2.
since that release contains a lot of breaking changes and the login flow in this application needs to be rewritten, this requires a substantial amount of work.
see #570 for the current state/progress made so far on fixing this situation.

### PR DESCRIPTION
**Pull request by w-lfchen**
closes #520 
closes #579 
closes #580 

- upgrade dependencies. Main change involves the migration to `librespot v0.5.0`
- migrate authentication workflow to OAuth implemented in (https://github.com/librespot-org/librespot/pull/1309)

## Next step
- handle Spotify Connect with user-provided `client_id`

### CODE REVIEW

**Review by ManiArasteh — COMMENTED** [review]
Thanks, But I don't want to accept!

**Comment by w-lfchen** [comment]
@ManiArasteh why not?

why would you not want to accept a pull request aiming to fix the issue **you** reported?

either provide a valid reason why or admit that you don't want to productively contribute to this project.
ignoring this question means the latter, i am tired of your behavior.

**Comment by ManiArasteh** [comment]
Because I can't. I can approve the pull requests but it's no use when I am not the author of repository.
For example, I can approve the PR opened in beaglesoftware/editor for example, but in a repository that I'm not the author, approving is no use, even If I am the contributor.
And...
Another reason is I didn't test it yet. And I can't because I don't have MSVC installed (I can if I change the.... platform, I think to windows-x86_64-gnu but for some crates, it needs GCC to compile
I don't have enough disk space to install MSVC, I can clean up my disk space, but with a lot of misery

**Comment by w-lfchen** [comment]
why didn't you just write that instead then?

**Comment by ManiArasteh** [comment]
And you opened it as a draft

**Comment by ManiArasteh** [comment]
It's better to add a `rev = "<oauth commit here>"`. Because some functions and variable may change in the future and cause some issues.

**Comment by w-lfchen** [comment]
why is the commit hash in the lockfile not sufficient?

if we want to update the dependency, we manually have to do so.
after updating dependencies, one should always **at least** test compilation

**Comment by ManiArasteh** [comment]
Look at librespot-org/librespot#1370 to see what's happening!
They cursed me for a letter I wrote.
The letter was **Hey, @roderickd, You didn't publish a new release**

**Comment by w-lfchen** [comment]
see https://github.com/aome510/spotify-player/issues/520#issuecomment-2409041468 for my response, i don't feel like typing out the same thing twice.

@ManiArasteh your behavior is killing my motivation to continue working on this pr, please stop.
i have already spent a lot of time working on this, time i could've used for literally anything else and i expect nothing but human decency and a somewhat productive environment in return, so please work towards clearing this extremely low bar, thank you.

**Comment by ManiArasteh** [comment]
I am testing it.

**Comment by w-lfchen** [comment]
this does not excuse your behavior.

**Comment by stanekondrej** [comment]
Hey @w-lfchen, I would love to contribute to this PR. If you want/need any help, could you please provide me with some pointers about what needs to be done? I've read #520 and got to this PR from your comment. I hope to be able to be of help.

**Comment by w-lfchen** [comment]
@stanekondrej thank you so much!
currently, we seem to be able to log in and generate a token, but the function `Spirc::new` fails when called [here](https://github.com/w-lfchen/spotify-player/blob/a502b088c197b901537be535b722a790fb2c01b0/spotify_player/src/streaming.rs#L223).

this is a problem on our side, the example application in librespot's repo that uses a `Spirc` works, see the "current state" section in the initial report for more information and a link; i'll update that section if i find something.

**Comment by stanekondrej** [comment]
> @stanekondrej thank you so much!
> currently, we seem to be able to log in and generate a token, but the function `Spirc::new` fails when called [here](https://github.com/w-lfchen/spotify-player/blob/a502b088c197b901537be535b722a790fb2c01b0/spotify_player/src/streaming.rs#L223).
> 
> this is a problem on our side, the example application in librespot's repo that uses a `Spirc` works, see the "current state" section in the initial report for more information and a link; i'll update that section if i find something.

I see, I've taken a quick look at the code you linked me to last night, but as it was late for me, I didn't really have time to investigate further. I'll take a closer look at it in the evening as I'm at school at the moment.

As for the comment by the author, if I understand it correctly, you mean that it would be better if you made the changes to the codebase since you have a better understanding of it. I completely get that, but I'd love to help with getting the respective changes implemented.

Thanks in advance

**Comment by aome510** [comment]
> As for the comment by the author, if I understand it correctly, you mean that it would be better if you made the changes to the codebase since you have a better understanding of it. I completely get that, but I'd love to help with getting the respective changes implemented.

Yeah, your understanding is correct. Feel free to take a look and implement the changes. Contributions are always welcomed and highly appreciated!!

**Review by w-lfchen — COMMENTED** [review]
i've updated the librespot dependencies to `0.5` since it's been released now

**Comment by juliamertz** [comment]
Hey @w-lfchen, i've managed to get your branch working by passing `Session::new(SessionConfig::default(), None)` to `Spirc::new` instead of the shared client session. Everything seems to be working well for me, though I'm not sure what the implications of this change are.

 I have tried finding the root cause of this problem, but no luck so far

**Comment by w-lfchen** [comment]
@juliamertz thank you!
i'm not sure either, but the application seems to work now, i've pushed a commit implementing your suggestion.
i'll do some cleanup and more tests and then ask for testers in the issue to see how stable this looks ^^

**Comment by w-lfchen** [comment]
removed a premature [commit](https://github.com/aome510/spotify-player/commit/685291dbdfbe7d0f193a66f692ea300dbdf1686f) i pushed.
it lead to scoping issues which i didn't fully test.

**Comment by tstenner** [comment]
I had to move the crypto provider initialization to the `main()` function, otherwise `spotify_player search` and `spotify_player authenticate` would abort.
Other than I didn't notice any regressions.

**Comment by ManiArasteh** [comment]
I think it is a bit difficult to implement OAuth2 in `spotify_player`. In `ncspot` is much simpler because it has less features than `spotify_player`

**Comment by apprehensions** [comment]
Restarting the client with this PR in use fails.
```
2024-10-21T16:18:26.905281Z  INFO client_request{request=RestartIntegratedClient}: spotify_player::streaming: Initializing a new integrated player with device_id=4e1c84e5-5c8d-43d5-886b-f35668191ea1
2024-10-21T16:18:26.905443Z  INFO client_request{request=RestartIntegratedClient}: spotify_player::streaming: Starting an integrated Spotify player using librespot's spirc protocol
2024-10-21T16:18:28.111510Z  INFO client_request{request=RestartIntegratedClient}: spotify_player::client: No playback found, trying to connect to an available device...
2024-10-21T16:18:28.111590Z  INFO client_request{request=RestartIntegratedClient}: spotify_player::client: Successfully handled the client request, took: 2152ms
2024-10-21T16:18:29.332896Z  WARN spotify_player::client: No device found. Please make sure you already setup Spotify Connect support as described in https://github.com/aome510/spotify-player#spotify-connect.
2024-10-21T16:18:29.332961Z  INFO spotify_player::client: Trying to connect to device (id=4e1c84e5-5c8d-43d5-886b-f35668191ea1)
2024-10-21T16:18:29.736301Z  WARN spotify_player::client: Connection failed (device_id=4e1c84e5-5c8d-43d5-886b-f35668191ea1): http error: status code 500 Internal Server Error
2024-10-21T16:18:30.952265Z  WARN spotify_player::client: No device found. Please make sure you already setup Spotify Connect support as described in https://github.com/aome510/spotify-player#spotify-connect.
2024-10-21T16:18:30.952332Z  INFO spotify_player::client: Trying to connect to device (id=4e1c84e5-5c8d-43d5-886b-f35668191ea1)
2024-10-21T16:18:31.443451Z  WARN spotify_player::client: Connection failed (device_id=4e1c84e5-5c8d-43d5-886b-f35668191ea1): http error: status code 404 Not Found
2024-10-21T16:18:32.660579Z  WARN spotify_player::client: No device found. Please make sure you already setup Spotify Connect support as described in https://github.com/aome510/spotify-player#spotify-connect.
2024-10-21T16:18:32.660653Z  INFO spotify_player::client: Trying to connect to device (id=4e1c84e5-5c8d-43d5-886b-f35668191ea1)
2024-10-21T16:18:33.152731Z  WARN spotify_player::client: Connection failed (device_id=4e1c84e5-5c8d-43d5-886b-f35668191ea1): http error: status code 404 Not Found
```

**Comment by Kek5chen** [comment]
@ManiArasteh its honestly exhausting trying to follow the issue and the PR with your nonsense around. I would like to ask you to please be quiet and stop saying unnecessary things that nobody has any use for. Thanks for opening the issue but if you have no more value to provide, please just let people do their work and be nothing more than grateful. Thanks everyone else for your contributions to OSS.

**Comment by ManiArasteh** [comment]
@Kek5chen Don't say nonsense. I said It's a bit difficult to implement OAuth2 in `spotify_player`. Is that off-topic?

**Comment by stanekondrej** [comment]
@ManiArasteh Your comment isn't necessarily off-topic, but it provides zero value to the discussion and development. You're just stating the obvious.

**Comment by ManiArasteh** [comment]
👮GitHub police on the way! (I mean I reported previous comment because of bullying and threatening)
Sorry, but not needed to block me, because I blocked you already.

> yes, nobody asked for your comment...

Nobody asked for my comment? Okay, your PR is useless, because nobody did not say to you to open a PR. 

> 98d8123 is your only contribution...

I will make more contributions, too. I will open a PR for implementing OAuth2, better than this.

> i'll leave any judgement of these stated facts up to the person reading this...

Okay, leave, and GitHub police will check your file more carefully (by reporting your comments)
I d
I really hate your behavior, don't forget this:
**_Privacy matters_**

> if this is the conclusion you came to after seeing everyone's reactions to your behavior here where nobody said they hate you as a person, everyone just disliking your behavior

Okay, stop replying to me, Mr. Behavior

> i don't want to block people on a platform for working together...

Okay, don't block if you stay alone.

> if i see one more unproductive comment from you, such as a defensive reply to this comment, i will block you...

If I see you've been contributed to this repository, I block you (It is no use, because I already blocked you)

> but i am too exhausted to put up with your behavior any longer...

Okay, don't work on this project if you're exhausted

**Comment by w-lfchen** [comment]
i blocked them, hopefully we can now work on this in peace; i apologize for not doing so earlier.

since they blocked me as well, i am no longer able to comment on #520 so please keep that in mind in case that becomes relevant.

**Comment by juliamertz** [comment]
> Restarting the client with this PR in use fails.

What OS are you using, and have you tried clearing your cache?

**Comment by apprehensions** [comment]
I feel like it is a security concern for the security token to be spat out in the logs.

```
2024-10-22T15:58:29.632356Z  INFO client_request{request=GetContext(Playlist(PlaylistId("2bQwC7mMG3f5UEjYuV5aoI")))}: spotify_player::client: Successfully handled the client request, took: 825ms
2024-10-22T17:50:55.083795Z  INFO client_request{request=Player(ResumePause)}: spotify_player::token: Getting new authentication token...
2024-10-22T17:50:55.234606Z  INFO client_request{request=Player(ResumePause)}: spotify_player::token: Got new token: Token { access_token: "no", expires_in: TimeDelta { secs: 3600, nanos: 0 }, expires_at: Some(noZ), refresh_token: None, scopes: {} }
2024-10-22T17:50:56.065487Z ERROR client_request{request=Player(ResumePause)}: spotify_player::client::handlers: Failed to handle client request: http error: status code 404 Not Found
2024-10-22T17:50:56.955014Z ERROR client_request{request=Player(Volume(75))}: spotify_player::client::handlers: Failed to handle client request: http error: status code 404 Not Found
2024-10-22T17:50:58.646625Z ERROR client_request{request=Player(StartPlayback(Context(Playlist(PlaylistId("2bQwC7mMG3f5UEjYuV5aoI")), Some(Uri("spotify:track:61IaHEbPKZj3I4APmkZSJd"))), None))}: spotify_player::client::handlers: Failed to handle client request: http error: status code 404 Not Found
2024-10-22T17:50:59.821922Z ERROR client_request{request=Player(StartPlayback(Context(Playlist(PlaylistId("2bQwC7mMG3f5UEjYuV5aoI")), Some(Uri("spotify:track:0Op3S08ZQiY7wpm4k9CVcZ"))), None))}: spotify_player::client::handlers: Failed to handle client request: http error: status code 404 Not Found
2024-10-22T17:51:18.645203Z ERROR client_request{request=Player(StartPlayback(Context(Playlist(PlaylistId("2bQwC7mMG3f5UEjYuV5aoI")), Some(Uri("spotify:track:0Op3S08ZQiY7wpm4k9CVcZ"))), None))}: spotify_player::client::handlers: Failed to handle client request: http error: status code 404 Not Found
2024-10-22T17:51:19.596061Z ERROR client_request{request=Player(StartPlayback(Context(Playlist(PlaylistId("2bQwC7mMG3f5UEjYuV5aoI")), Some(Uri("spotify:track:1QkzZUYcm9IzSsEY1HieDS"))), None))}: spotify_player::client::handlers: Failed to handle client request: http error: status code 404 Not Found
2024-10-22T17:51:20.612873Z ERROR client_request{request=Player(StartPlayback(Context(Playlist(PlaylistId("2bQwC7mMG3f5UEjYuV5aoI")), Some(Uri("spotify:track:4zwQYI1yLuUTR6AspMcKBM"))), None))}: spotify_player::client::handlers: Failed to handle client request: http error: status code 404 Not Found
```

> What OS are you using, and have you tried clearing your cache?

Alpine Linux edge, and no.

**Comment by aome510** [comment]
I might have sometime this weekend and will start looking into the remaining items. Please keep me posted on the progress or if anyone is working on those already. 

Hopefully, we can push a new release by this week 🤞🤞.

**Comment by juliamertz** [comment]
> I've cleared cache. Simply restarting the client by pressing `R` causes the issue.
 
Ah okay it seems like i misunderstood, I'm unable to reproduce this on my system though 😕.

**Comment by apprehensions** [comment]
> Our review of the account named in your report has concluded. We have determined that one or more violations of GitHub’s Terms of Service have occurred and have taken appropriate action in response.

Good riddance.

**Comment by aome510** [comment]
I've updated the PR. The new workflow seems to work well for me locally. Still some TODOs left but otherwise, looks promising. Those TODOs can be handled in a separate PR instead.

**Comment by aome510** [comment]
Merged this PR 🚀 🚀 🚀 . Kudos to everyone for making this happen. 

The next step gonna be handling client-id scoping for [Spotify Connect feature](https://github.com/aome510/spotify-player?tab=readme-ov-file#spotify-connect)

**Pull request merged**
