### PR TITLE
Add Mute command

### PR DESCRIPTION
**Pull request by BKasin**
Resolves https://github.com/aome510/spotify-player/issues/243.

Add the ability to immediately set volume to 0% as requested in #243. I bound it to _ since "Shift + -" made sense to me, as it's basically super volume decrease.

### CODE REVIEW

**Comment by aome510** [comment]
Hi @BKasin, thanks for the PR. Ideally, `mute` should be a toggle command. Can you update the PR to support that?

**Comment by BKasin** [comment]
@aome510 I agree that that would be preferable, but am not sure how to best implement it.

**Comment by aome510** [comment]
> @aome510 I agree that that would be preferable, but am not sure how to best implement it.

Yeah, it's kinda tricky. One way is to add a new field called `MuteState: Option<u32>` in https://github.com/aome510/spotify-player/blob/master/spotify_player/src/state/player.rs#L5-L15, which is `None` is not mute and `Some(previous_volume_percent)` if is mute. Handling "mute toggle" command will involve updating that state and sending a `PlayerRequest::Volume` request.

**Comment by BKasin** [comment]
Thank you for the guidance, I definitely was over-complicating it mentally.

**Review by aome510 — APPROVED** [review]
LGTM! Thanks.

It would be nice to also have UI for the mute functionality. Can you change https://github.com/aome510/spotify-player/blob/05fbda6fe0f5d1e233ef03f8008968f7725e46bf/spotify_player/src/ui/playback.rs#L182-L188 as well?

Maybe  display`volume: old_percent% (muted)` if muted or `volume: current_percent%` if not.

**Comment by BKasin** [comment]
Yeah, a little later today when I get home I'll do that.

**Comment by aome510** [comment]
Thanks @BKasin, after testing the change locally, I thought that the command logic could be simplified a bit more and we also need to handle the case when user increases/decreases the volume on mute. I updated the PR according to implement the above changes in https://github.com/aome510/spotify-player/pull/253/commits/a3930acbca1fb1a77e371b9d11101747e84e407a

**Comment by BKasin** [comment]
Ah, yeah that is definitely a lot better. Thank you!

**Pull request merged**
